In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {'Temperature':['Hot','Cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','Cold'],
        'Color':['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow'],
        'Target':[1,1,1,0,1,0,1,0,1,1]}
df = pd.DataFrame(data)
df

  Temperature   Color  Target
0         Hot     Red       1
1        Cold  Yellow       1
2    Very Hot    Blue       1
3        Warm    Blue       0
4         Hot     Red       1
5        Warm  Yellow       0
6        Warm     Red       1
7         Hot  Yellow       0
8         Hot  Yellow       1
9        Cold  Yellow       1

In [14]:
### One Hot Encoding

df_ohe = df.copy()

ohe = pd.get_dummies(df_ohe,columns=['Color'],drop_first=True,prefix='C_',dtype = 'int')

ohe.insert(loc=2,column='Color',value=df.Color.values)

ohe

  Temperature  Target   Color  C__Red  C__Yellow
0         Hot       1     Red       1          0
1        Cold       1  Yellow       0          1
2    Very Hot       1    Blue       0          0
3        Warm       0    Blue       0          0
4         Hot       1     Red       1          0
5        Warm       0  Yellow       0          1
6        Warm       1     Red       1          0
7         Hot       0  Yellow       0          1
8         Hot       1  Yellow       0          1
9        Cold       1  Yellow       0          1

In [21]:
# using OneHotEncoder

from sklearn.preprocessing import OneHotEncoder

# create ohe instance
encoder = OneHotEncoder(sparse_output=False,drop='first')

# fit and transform
encoded_data = encoder.fit_transform(df[['Color']])

# create the dataframe

encoded_df = pd.DataFrame(encoded_data,columns=encoder.get_feature_names_out(['Color']))

# concat the data
df_encoded =pd.concat([df,encoded_df],axis=1)

df_encoded

  Temperature   Color  Target  Color_Red  Color_Yellow
0         Hot     Red       1        1.0           0.0
1        Cold  Yellow       1        0.0           1.0
2    Very Hot    Blue       1        0.0           0.0
3        Warm    Blue       0        0.0           0.0
4         Hot     Red       1        1.0           0.0
5        Warm  Yellow       0        0.0           1.0
6        Warm     Red       1        1.0           0.0
7         Hot  Yellow       0        0.0           1.0
8         Hot  Yellow       1        0.0           1.0
9        Cold  Yellow       1        0.0           1.0

In [24]:
### binary encoding
import category_encoders as ce

be = ce.BinaryEncoder(cols=['Temperature'])

be_df = be.fit_transform(df['Temperature'])

binary_df = pd.concat([df,be_df],axis =1)

binary_df

  Temperature   Color  Target  Temperature_0  Temperature_1  Temperature_2
0         Hot     Red       1              0              0              1
1        Cold  Yellow       1              0              1              0
2    Very Hot    Blue       1              0              1              1
3        Warm    Blue       0              1              0              0
4         Hot     Red       1              0              0              1
5        Warm  Yellow       0              1              0              0
6        Warm     Red       1              1              0              0
7         Hot  Yellow       0              0              0              1
8         Hot  Yellow       1              0              0              1
9        Cold  Yellow       1              0              1              0

In [ ]:
!pip install category-encoders